version: "3"
services:
  jupyter:
    image: johnnyvm90/jupyter:latest
    build:
      context: '.'
    ports:
      - "8888:8888"
    volumes:
      - ./config.py:/etc/jupyter/config.py:ro
      - ./notebook:/usr/share/notebook
